version: '3'

services:
  orders:
    image: orders:latest
    depends_on:
      - mongo
      - phones
    restart: on-failure
    environment:
      PHONES_BASE_URL: http://phones:8080
      MONGODB_HOST: mongo
    ports:
     - "9091:9090"

  phones:
    image: phones:latest
    depends_on:
      - phones-db
    restart: on-failure
    environment:
      DB_HOST: phones-db
    ports:
     - "8082:8080"

  phones-db:
    image: phones-db:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
     - "3306:3306"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
